
<!DOCTYPE HTML>

<html lang="en" class="_theme-default">

<head>
  <meta charset="utf-8">
  <title>6. Error Handling - Express - W3cubDocs</title>
  
  <meta name="description" content="Error Handling refers to how Express catches and processes errors that occur both synchronously and asynchronously. Express comes with a default &hellip;">
  <meta name="keywords" content="error, handling, express">
  <meta name="HandheldFriendly" content="True">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="mobile-web-app-capable" content="yes">
  
  <link rel="canonical" href="https://docs.w3cub.com/express/guide/error-handling.html">
  <link href="/favicon.png" rel="icon">
  <link rel="stylesheet" type="text/css" href="/assets/application-9c7b0d969c0ce639a6c01c2badcdd81667c7c66206aa3d0fccc5cb0585fb1b912dab72ea882101d18010680927514b4b77b107282db8f756fbf63301fe9c88b0.css">
  <script type="text/javascript" src="/assets/application-79c555f6b25481fffac2cac30a7f3e54e608ca09e9e8e42bb1790095ba6d0fcace47d6bc624ddce952c70370892f2d46864f89e6943d4f7f7ff16c8a3231a91a.js"></script>
  <script src="/json/express.js"></script>
  
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-R3WC07G3GB"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-R3WC07G3GB');
</script>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2572770204602497"
     crossorigin="anonymous"></script>
<script async custom-element="amp-auto-ads"
  src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js">
</script>


</head>

<body class="docs">
	<amp-auto-ads type="adsense"
              data-ad-client="ca-pub-2572770204602497">
	</amp-auto-ads>
	<div class="_app">
	<header class="_header">

  <a class="_home-link" href="/" ></a>
  <a class="_menu-link"></a>
  <h1 class="_logo">
    <a href="/" class="_nav-link" title="API Documentation Browser">W3cubDocs</a>
  </h1>
  
  <span class="_logo-sub-nav">/</span><span class="_logo-sub-nav"><a href="/express/" class="_nav-link" title="" style="margin-left:0;">Express</a></span>
  
  <nav class="_nav">
    <a href="https://tools.w3cub.com/?_sp=docs" target="_blank" class="_nav-link ">W3cubTools</a>
    <a href="/cheatsheets/" class="_nav-link ">Cheatsheets</a>
    <a href="/about/" class="_nav-link ">About</a>
  </nav>
</header>
	<section class="_sidebar">
		
		<form class="_search">
		  <input type="search" class="_search-input" placeholder="Search&hellip;" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" maxlength="20">
		  <a class="_search-clear"></a>
		  <div class="_search-tag"></div>
		</form>
		
		<div class="_list-wrap">
			<div class="_list">
			
			</div>
		</div>
	</section>
	<section class="_container ">
		<div class="_content">
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="6861657091"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
			<div class="_page _express">
				
				
<h1 id="error-handling" data-level="6">Error Handling</h1> <p><em>Error Handling</em> refers to how Express catches and processes errors that occur both synchronously and asynchronously. Express comes with a default error handler so you don’t need to write your own to get started.</p> <h2 id="catching-errors">Catching Errors</h2> <p>It’s important to ensure that Express catches all errors that occur while running route handlers and middleware.</p> <p>Errors that occur in synchronous code inside route handlers and middleware require no extra work. If synchronous code throws an error, then Express will catch and process it. For example:</p> <pre data-language="js">app.get('/', (req, res) =&gt; {
  throw new Error('BROKEN') // Express will catch this on its own.
})
</pre> <p>For errors returned from asynchronous functions invoked by route handlers and middleware, you must pass them to the <code>next()</code> function, where Express will catch and process them. For example:</p> <pre data-language="js">app.get('/', (req, res, next) =&gt; {
  fs.readFile('/file-does-not-exist', (err, data) =&gt; {
    if (err) {
      next(err) // Pass errors to Express.
    } else {
      res.send(data)
    }
  })
})
</pre> <p>Starting with Express 5, route handlers and middleware that return a Promise will call <code>next(value)</code> automatically when they reject or throw an error. For example:</p> <pre data-language="js">app.get('/user/:id', async (req, res, next) =&gt; {
  const user = await getUserById(req.params.id)
  res.send(user)
})
</pre> <p>If <code>getUserById</code> throws an error or rejects, <code>next</code> will be called with either the thrown error or the rejected value. If no rejected value is provided, <code>next</code> will be called with a default Error object provided by the Express router.</p> <p>If you pass anything to the <code>next()</code> function (except the string <code>'route'</code>), Express regards the current request as being an error and will skip any remaining non-error handling routing and middleware functions.</p> <p>If the callback in a sequence provides no data, only errors, you can simplify this code as follows:</p> <pre data-language="js">app.get('/', [
  function (req, res, next) {
    fs.writeFile('/inaccessible-path', 'data', next)
  },
  function (req, res) {
    res.send('OK')
  }
])
</pre> <p>In the above example <code>next</code> is provided as the callback for <code>fs.writeFile</code>, which is called with or without errors. If there is no error the second handler is executed, otherwise Express catches and processes the error.</p> <p>You must catch errors that occur in asynchronous code invoked by route handlers or middleware and pass them to Express for processing. For example:</p> <pre data-language="js">app.get('/', (req, res, next) =&gt; {
  setTimeout(() =&gt; {
    try {
      throw new Error('BROKEN')
    } catch (err) {
      next(err)
    }
  }, 100)
})
</pre> <p>The above example uses a <code>try...catch</code> block to catch errors in the asynchronous code and pass them to Express. If the <code>try...catch</code> block were omitted, Express would not catch the error since it is not part of the synchronous handler code.</p> <p>Use promises to avoid the overhead of the <code>try...catch</code> block or when using functions that return promises. For example:</p> <pre data-language="js">app.get('/', (req, res, next) =&gt; {
  Promise.resolve().then(() =&gt; {
    throw new Error('BROKEN')
  }).catch(next) // Errors will be passed to Express.
})
</pre> <p>Since promises automatically catch both synchronous errors and rejected promises, you can simply provide <code>next</code> as the final catch handler and Express will catch errors, because the catch handler is given the error as the first argument.</p> <p>You could also use a chain of handlers to rely on synchronous error catching, by reducing the asynchronous code to something trivial. For example:</p> <pre data-language="js">app.get('/', [
  function (req, res, next) {
    fs.readFile('/maybe-valid-file', 'utf-8', (err, data) =&gt; {
      res.locals.data = data
      next(err)
    })
  },
  function (req, res) {
    res.locals.data = res.locals.data.split(',')[1]
    res.send(res.locals.data)
  }
])
</pre> <p>The above example has a couple of trivial statements from the <code>readFile</code> call. If <code>readFile</code> causes an error, then it passes the error to Express, otherwise you quickly return to the world of synchronous error handling in the next handler in the chain. Then, the example above tries to process the data. If this fails then the synchronous error handler will catch it. If you had done this processing inside the <code>readFile</code> callback then the application might exit and the Express error handlers would not run.</p> <p>Whichever method you use, if you want Express error handlers to be called in and the application to survive, you must ensure that Express receives the error.</p> <h2 id="the-default-error-handler">The default error handler</h2> <p>Express comes with a built-in error handler that takes care of any errors that might be encountered in the app. This default error-handling middleware function is added at the end of the middleware function stack.</p> <p>If you pass an error to <code>next()</code> and you do not handle it in a custom error handler, it will be handled by the built-in error handler; the error will be written to the client with the stack trace. The stack trace is not included in the production environment.</p> <div class="doc-box doc-info"> <p>Set the environment variable <code>NODE_ENV</code> to <code>production</code>, to run the app in production mode.</p> </div> <p>When an error is written, the following information is added to the response:</p> <ul> <li>The <code>res.statusCode</code> is set from <code>err.status</code> (or <code>err.statusCode</code>). If this value is outside the 4xx or 5xx range, it will be set to 500.</li> <li>The <code>res.statusMessage</code> is set according to the status code.</li> <li>The body will be the HTML of the status code message when in production environment, otherwise will be <code>err.stack</code>.</li> <li>Any headers specified in an <code>err.headers</code> object.</li> </ul> <p>If you call <code>next()</code> with an error after you have started writing the response (for example, if you encounter an error while streaming the response to the client) the Express default error handler closes the connection and fails the request.</p> <p>So when you add a custom error handler, you must delegate to the default Express error handler, when the headers have already been sent to the client:</p> <pre data-language="js">function errorHandler (err, req, res, next) {
  if (res.headersSent) {
    return next(err)
  }
  res.status(500)
  res.render('error', { error: err })
}
</pre> <p>Note that the default error handler can get triggered if you call <code>next()</code> with an error in your code more than once, even if custom error handling middleware is in place.</p> <h2 id="writing-error-handlers">Writing error handlers</h2> <p>Define error-handling middleware functions in the same way as other middleware functions, except error-handling functions have four arguments instead of three: <code>(err, req, res, next)</code>. For example:</p> <pre data-language="js">app.use((err, req, res, next) =&gt; {
  console.error(err.stack)
  res.status(500).send('Something broke!')
})
</pre> <p>You define error-handling middleware last, after other <code>app.use()</code> and routes calls; for example:</p> <pre data-language="js">const bodyParser = require('body-parser')
const methodOverride = require('method-override')

app.use(bodyParser.urlencoded({
  extended: true
}))
app.use(bodyParser.json())
app.use(methodOverride())
app.use((err, req, res, next) =&gt; {
  // logic
})
</pre> <p>Responses from within a middleware function can be in any format, such as an HTML error page, a simple message, or a JSON string.</p> <p>For organizational (and higher-level framework) purposes, you can define several error-handling middleware functions, much as you would with regular middleware functions. For example, to define an error-handler for requests made by using <code>XHR</code> and those without:</p> <pre data-language="js">const bodyParser = require('body-parser')
const methodOverride = require('method-override')

app.use(bodyParser.urlencoded({
  extended: true
}))
app.use(bodyParser.json())
app.use(methodOverride())
app.use(logErrors)
app.use(clientErrorHandler)
app.use(errorHandler)
</pre> <p>In this example, the generic <code>logErrors</code> might write request and error information to <code>stderr</code>, for example:</p> <pre data-language="js">function logErrors (err, req, res, next) {
  console.error(err.stack)
  next(err)
}
</pre> <p>Also in this example, <code>clientErrorHandler</code> is defined as follows; in this case, the error is explicitly passed along to the next one.</p> <p>Notice that when <em>not</em> calling “next” in an error-handling function, you are responsible for writing (and ending) the response. Otherwise those requests will “hang” and will not be eligible for garbage collection.</p> <pre data-language="js">function clientErrorHandler (err, req, res, next) {
  if (req.xhr) {
    res.status(500).send({ error: 'Something failed!' })
  } else {
    next(err)
  }
}
</pre> <p>Implement the “catch-all” <code>errorHandler</code> function as follows (for example):</p> <pre data-language="js">function errorHandler (err, req, res, next) {
  res.status(500)
  res.render('error', { error: err })
}
</pre> <p>If you have a route handler with multiple callback functions you can use the <code>route</code> parameter to skip to the next route handler. For example:</p> <pre data-language="js">app.get('/a_route_behind_paywall',
  (req, res, next) =&gt; {
    if (!req.user.hasPaid) {
      // continue handling this request
      next('route')
    } else {
      next()
    }
  }, (req, res, next) =&gt; {
    PaidContent.find((err, doc) =&gt; {
      if (err) return next(err)
      res.json(doc)
    })
  })
</pre> <p>In this example, the <code>getPaidContent</code> handler will be skipped but any remaining handlers in <code>app</code> for <code>/a_route_behind_paywall</code> would continue to be executed.</p> <div class="doc-box doc-info"> <p>Calls to <code>next()</code> and <code>next(err)</code> indicate that the current handler is complete and in what state. <code>next(err)</code> will skip all remaining handlers in the chain except for those that are set up to handle errors as described above.</p> </div>
<div class="_attribution">
  <p class="_attribution-p">
    © 2017 StrongLoop, IBM, and other expressjs.com contributors.<br>Licensed under the Creative Commons Attribution-ShareAlike License v3.0.<br>
    <a href="https://expressjs.com/en/guide/error-handling.html" class="_attribution-link">https://expressjs.com/en/guide/error-handling.html</a>
  </p>
</div>

				
			</div>
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="1992473792"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
		</div>
	</section>

	</div>
	<svg style="display:none">
		<symbol id="icon-dir"><svg viewBox="0 0 20 20"><path d="M15 10c0 .3-.305.515-.305.515l-8.56 5.303c-.625.41-1.135.106-1.135-.67V4.853c0-.777.51-1.078 1.135-.67l8.56 5.305S15 9.702 15 10z"/></svg></symbol>
	  </svg>
</body>
</html>
